FORMAT: 1A
HOST: http://api.pricerobot.org/v1

# Price robot Data API

Price robot APP商品及价格数据请求API

## 查询商品详情 [/p/{pid}]

### 查询商品详情 [GET]

得到一个已经存在的商品的价格。
第一版只返回最新20条。
参数q，可以是一个url也可以是一个keywordx 

+ Parameters
    + pid - 查询Product id

+ Response 200 (application/json)

        {
            "pid": "123",
            "photo": "http://www.fakeimage.com/1.png",
            "created_at": "2015-08-05T08:40:51.620Z",
            "title": "サッポロ 麦とホップ 350ml×24本",
            "price": "￥ 11",
            "prices": {
                "highest":2767,
                "lowest":2440,
                "average":2748,
                "current":2767,
                "history":
                [
                    "2017-01-01": 2766,
                    "2017-01-02": 2765,
                    "2017-01-03": 2764,
                    "2017-01-04": 2763
                ]
            }
        }


## 创建商品条目 [/p/]

### 创建商品条目 [POST]

接收一个amazon的url，创建一条新的商品条目。
虽然这个条件可能已经被创建过。

+ Attributes
    + url:"https://www.amazon.co.jp/dp/B01J41JLTQ" (string, required)
    
+ Request (application/x-www-form-urlencoded)

+ Response 200 (text/plain)

    + Body

            {
                "asin": "B011122123",
                "error": ""
            }